### ISSUE TITLE
ParallelIndexer consumers die on exceptions

### ISSUE THREAD

**Issue by bobobo1618** [dermotte/LIRE#39]
I'm running `ParallelIndexer` on a large number of files, some of which apparently have issues. The `Consumer`s throw NullPointerExceptions occasionally but when this happens, they die and don't respawn. Eventually, all of them die and the files don't end up processed.

An example exception is this:

```
Exception in thread "Consumer-12" java.lang.NullPointerException
        at net.semanticmetadata.lire.builders.GlobalDocumentBuilder.extractGlobalFeature(GlobalDocumentBuilder.java:188)
        at net.semanticmetadata.lire.builders.GlobalDocumentBuilder.getGlobalDescriptorFields(GlobalDocumentBuilder.java:210)
        at net.semanticmetadata.lire.builders.GlobalDocumentBuilder.createDescriptorFields(GlobalDocumentBuilder.java:258)
        at net.semanticmetadata.lire.indexers.parallel.ParallelIndexer$Consumer.run(ParallelIndexer.java:1194)
        at java.lang.Thread.run(Thread.java:745)
```

It'd be better if something high up the stack could catch all exceptions and log them then continue to the next file instead.

**Comment by dermotte** [comment]
Confirmed! Thanks for the fix too, I just merged it in! cheers, Majthias
