### ISSUE TITLE
Is a GenericFastImageSearcher thread safe for different images?

### ISSUE THREAD

**Issue by bukebuhao** [dermotte/LIRE#46]
If I have two multiple threads accessing a GenericFastImageSearcher, but one is error。
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
	at java.util.LinkedList$ListItr.next(LinkedList.java:888)
	at net.semanticmetadata.lire.aggregators.VLAD.createVectorRepresentation(VLAD.java:69)
	at net.semanticmetadata.lire.searchers.GenericFastImageSearcher.search(GenericFastImageSearcher.java:517)

**Comment by dermotte** [comment]
Hi!

No, it is not thread safe. In the sense of what happens in the back office of all this I recommend bundling searches rather than running them concurrently. 

regards,
Mathias

**Comment by bukebuhao** [comment]
thank you!
