### ISSUE TITLE
Demo doesn't work - 'Lucene50' does not exist exception

### ISSUE THREAD

**Issue by Aleyasen** [dermotte/LIRE#48]
I ran the demo using ```java -jar liredemo-1.0b4.jar```
but I got the following exception after importing images. 
```
Exception in thread "Thread-6" java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene62.Lucene62Codec
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
        at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
        at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
        at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:115)
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:149)
        at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:136)
        at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:111)
        at net.semanticmetadata.lire.indexers.parallel.ParallelIndexer.run(ParallelIndexer.java:748)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [IDVersion]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
        at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
        at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:167)
        at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:82)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
        ... 10 more
```

My java version:
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by dermotte** [comment]
Hi! It's clearly the wrong version of Lucene packaged. Where did you download the demo? I can easily fix the libs if I know where. cheers, Mathias

**Comment by Aleyasen** [comment]
Thanks for the quick reply @dermotte 
This is the URL ```http://www.itec.uni-klu.ac.at/~mlux/lire-release/liredemo-1.0b4.jar```

**Comment by dermotte** [comment]
I'll update it asap. thanks for the note.
