### ISSUE TITLE
An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.

### ISSUE THREAD

**Issue by scelesticsiva** [dermotte/LIRE#49]
When i was trying to run the demo from the link 

http://www.itec.uni-klu.ac.at/~mlux/lire-release/liredemo-1.0b4.jar

I am getting the following error,

Cannot instantiate SPI class: org.apache.lucene.codecs.lucene62.Lucene62Codec
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:115)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:149)
	at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:136)
	at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:111)
	at net.semanticmetadata.lire.indexers.parallel.ParallelIndexer.run(ParallelIndexer.java:748)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [IDVersion]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
	at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:167)
	at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	... 10 more

I am using 

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Any help would be much appreciated

**Comment by dermotte** [comment]
changed from all in jar to gradle on the release page. use the zip package.
