### ISSUE TITLE
IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.

### ISSUE THREAD

**Issue by ypkkhatri** [dermotte/LIRE#56]
I'm trying to create new index but its throwing exception on SPI below:
```
Exception in thread "main" java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene62.Lucene62Codec
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:121)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:151)
	at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:145)
	at net.semanticmetadata.lire.utils.LuceneUtils.createIndexWriter(LuceneUtils.java:120)
	at net.semanticmetadata.lire.indexers.parallel.ParallelIndexer.run(ParallelIndexer.java:749)
	at com.lire.project86610.IndexService.createIndex(IndexService.java:110)
	at com.lire.project86610.Main.main(Main.java:33)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [IDVersion]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
	at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:167)
	at org.apache.lucene.codecs.lucene62.Lucene62Codec.<init>(Lucene62Codec.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	... 11 more

```

Code:
```
public static void main(String args[]) {
	ParallelIndexer pin = new ParallelIndexer(6, "MyIndex", "/home/myimages");
	pin.addExtractor(ColorLayout.class);
	pin.addExtractor(CEDD.class);
	pin.addExtractor(FCTH.class);
	pin.addExtractor(JCD.class);
	pin.addExtractor(ScalableColor.class);
	pin.addExtractor(EdgeHistogram.class);
	pin.addExtractor(AutoColorCorrelogram.class);
	pin.addExtractor(Tamura.class);
	pin.addExtractor(Gabor.class);
	pin.addExtractor(SimpleColorHistogram.class);
	pin.addExtractor(OpponentHistogram.class);
	pin.addExtractor(JointHistogram.class);
	pin.addExtractor(LuminanceLayout.class);
	pin.addExtractor(PHOG.class);
	pin.addExtractor(ACCID.class);
	pin.addExtractor(COMO.class);
	pin.setCustomDocumentBuilder(MetadataBuilder.class);
	pin.run();
}
```

**Comment by dermotte** [comment]
This does not seem to be an issue of LIRE, but is most likely coming from the use of it. Please use the issues for bugs of LIRE. Problems you encounter are to be handled in the mailing list. For that please include more information as this problem of yours is not reproducible?
