### ISSUE TITLE
Lucene v8.0.0

### ISSUE THREAD

**Issue by Campano** [dermotte/LIRE#62]
Hi,

I'm using LIRE in a project that already packages `lucene-core-8.0.0.jar` and I'm having trouble finding a compatible lucene-free lire jar.

1. can I find a lucene-free lire jar ?
2. how could I repackage LIRE to work with lucene 8 ?

Btw, I'm having the following Exeptions on a simple `Codec cd = Codec.getDefault();` **once I include the lire jar** from `http://www.itec.uni-klu.ac.at/~mlux/lire-release/lire-nightly.zip` :

```
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/codecs/lucene50/Lucene50Codec
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
	at com.simplicite.objects.Demo.DemoClient.unitTests(DemoClient.java:21)
	at com.simplicite.objects.System.ObjectInternal.runUnitTests(ObjectInternal.java:1045)
	... 44 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.codecs.lucene50.Lucene50Codec
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1363)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)
	... 55 more
```

**Comment by Campano** [comment]
https://github.com/dermotte/LIRE/pull/63
